begin;

create temporary table seed_events (
  slug text,
  title text,
  category_label text,
  category_slug text,
  status text,
  start_time timestamptz,
  end_time timestamptz,
  venue_name text,
  venue_address text,
  locality text,
  ticket_price numeric,
  is_free boolean,
  registration_url text,
  organizer_name text,
  image_url text,
  short_description text,
  description text,
  source_label text,
  source_url text,
  tags text[]
);

insert into seed_events (
  slug, title, category_label, category_slug, status, start_time, end_time,
  venue_name, venue_address, locality, ticket_price, is_free,
  registration_url, organizer_name, image_url,
  short_description, description, source_label, source_url, tags
)
values
(
  'filmish-play-shivam-dhall-raja-subramaniyam-jaipur-apr-2026',
  'Filmish – A Play by Shivam Dhall & Raja Subramaniyam',
  'Theatre / Performing Arts',
  'art-culture',
  'past',
  '2026-04-11 18:30:00+05:30',
  '2026-04-11 20:00:00+05:30',
  'Rajasthan International Centre – Main Auditorium',
  'Sansthan Path, JLN Marg, Jaipur, Rajasthan 302017',
  'jhalana-doongri',
  null,
  false,
  'https://ricjaipur.org/event.html',
  'Rajasthan International Centre',
  null,
  'Filmish is a theatrical play written and performed by Shivam Dhall and Raja Subramaniyam at the RIC Main Auditorium.',
  'Rajasthan International Centre presents Filmish, a theatrical production by Shivam Dhall and Raja Subramaniyam at the iconic Main Auditorium in Jaipur.',
  'Rajasthan International Centre Official Calendar',
  'https://ricjaipur.org/Uploads/Downloads/CalendarOfEvents.pdf',
  array['theatre','play','performing arts','jaipur']
),
(
  'bhuwin-experience-noor-e-daastaan-jaipur-apr-2026',
  'Bhuwin Experience – Noor-e-Daastaan',
  'Concert / Live Music',
  'music-events',
  'past',
  '2026-04-12 19:00:00+05:30',
  null,
  'Rajasthan International Center',
  'Bhamashah State Data Centre Block-C, Jhalana Doongri, Jaipur, Rajasthan 302004',
  'jhalana-doongri',
  null,
  false,
  'https://www.bandsintown.com/c/jaipur-india',
  null,
  null,
  'A live concert experience by artist Bhuwin – Noor-e-Daastaan – at the Rajasthan International Center, Jaipur.',
  'Bhuwin brings his evocative live experience Noor-e-Daastaan to Jaipur. A soulful indie live set at Rajasthan International Center.',
  'Bandsintown',
  'https://www.bandsintown.com/c/jaipur-india',
  array['concert','live music','indie','jaipur']
),
(
  'lagan-mandap-summer-exhibition-jaipur-apr-2026',
  'Lagan Mandap Summer Exhibition 2026',
  'Exhibition / Fashion',
  'exhibitions',
  'upcoming',
  '2026-04-14 10:30:00+05:30',
  '2026-04-15 21:00:00+05:30',
  'Birla Auditorium',
  'BM Birla Auditorium, Statue Circle, C Scheme, Rambagh, Jaipur, Rajasthan 302015',
  'c-scheme',
  0,
  true,
  'https://allevents.in/jaipur/lagan-mandap-summer-exhibition/80004582808600',
  'Lagan Mandap',
  'https://cdn2.allevents.in/thumbs/thumb69be47bdda5fe.jpg',
  'Summer fashion shopping extravaganza featuring ethnic wear, designer outfits, wedding collections, handcrafted jewellery and accessories.',
  'Get ready to experience the ultimate summer fashion destination at the Lagan Mandap Exhibition in Jaipur with designer outfits, wedding collections, jewellery and lifestyle products.',
  'AllEvents.in',
  'https://allevents.in/jaipur/lagan-mandap-summer-exhibition/80004582808600',
  array['exhibition','fashion','ethnic wear','bridal','shopping','jaipur']
),
(
  'ghazals-more-pratibha-singh-baghel-deepak-pandit-jaipur-apr-2026',
  'Ghazals & More – Pratibha Singh Baghel & Deepak Pandit',
  'Concert / Classical Music',
  'music-events',
  'upcoming',
  '2026-04-17 18:30:00+05:30',
  '2026-04-17 20:30:00+05:30',
  'Rajasthan International Centre – Main Auditorium',
  'Sansthan Path, JLN Marg, Jaipur, Rajasthan 302017',
  'jhalana-doongri',
  null,
  false,
  'https://in.bookmyshow.com/plays/rajasthan-international-centre/ET00363555',
  'Rajasthan International Centre',
  null,
  'An enchanting evening of Ghazals and classical music by vocalist Pratibha Singh Baghel and violinist Deepak Pandit.',
  'Rajasthan International Centre presents Ghazals & More featuring Pratibha Singh Baghel and Deepak Pandit as part of the Foundation Day Celebrations.',
  'Rajasthan International Centre Official Calendar',
  'https://ricjaipur.org/Uploads/Downloads/CalendarOfEvents.pdf',
  array['ghazal','classical music','concert','jaipur']
),
(
  'ar-rahman-harmony-of-hearts-jaipur-apr-2026',
  'A.R. Rahman – Harmony of Hearts',
  'Concert / Live Music',
  'music-events',
  'upcoming',
  '2026-04-18 19:00:00+05:30',
  '2026-04-18 22:00:00+05:30',
  'JECC Ground',
  'Jaipur Exhibition & Convention Centre, RIICO Industrial Area, Sitapura, Jaipur, Rajasthan 302022',
  'sitapura',
  1999,
  false,
  'https://allevents.in/jaipur/ar-rahman-harmony-of-hearts/4100029817587244',
  null,
  'https://ilovejaipur.city/media/events/2026/01/19_20260127_205003.jpg',
  'A.R. Rahman performs live in Jaipur – a Sufi-inspired spectacle of soul-stirring music weaving love, harmony and emotion.',
  'The legendary A.R. Rahman brings his Harmony of Hearts tour to Jaipur at JECC Ground for an unforgettable live concert experience.',
  'ilovejaipur.city / AllEvents.in',
  'https://ilovejaipur.city/events/ar-rahman-harmony-of-hearts-apr-2026/',
  array['concert','AR Rahman','Sufi','live music','JECC','jaipur']
),
(
  'smc-summit-3-jaipur-apr-2026',
  'SMC Summit 3.0 – 2026',
  'Conference / Education',
  'business-education',
  'upcoming',
  '2026-04-18 11:00:00+05:30',
  '2026-04-19 21:00:00+05:30',
  'Rajasthan International Center',
  'Bhamashah State Data Centre Block-C, Jhalana Doongri, Jaipur, Rajasthan 302004',
  'jhalana-doongri',
  500,
  false,
  'https://ilovejaipur.city/events/smc-summit-30-2026/',
  'SortMyCollege',
  'https://ilovejaipur.city/media/events/2026/03/19_20260327_111834.jpg',
  'India''s leading edutainment festival — two power-packed days of keynotes, creator panels, career workshops and mentorship.',
  'SMC Summit 3.0 brings together students, creators, founders and industry leaders for two days of keynotes, workshops, mentorship and networking.',
  'ilovejaipur.city',
  'https://ilovejaipur.city/events/smc-summit-30-2026/',
  array['summit','education','students','entrepreneurs','career','jaipur']
),
(
  'viksit-rajasthan-2047-governance-talk-jaipur-apr-2026',
  'Viksit Rajasthan @ 2047 – Governance Transformed (Talk by Chief Secretary)',
  'Talk / Seminar',
  'business-education',
  'upcoming',
  '2026-04-18 17:00:00+05:30',
  '2026-04-18 18:45:00+05:30',
  'RIC Mini Auditorium-1',
  'Rajasthan International Centre, Sansthan Path, JLN Marg, Jaipur, Rajasthan 302017',
  'jhalana-doongri',
  0,
  true,
  'https://ricjaipur.org/event.html',
  'Rajasthan International Centre',
  null,
  'A talk by V. Srinivas, Chief Secretary of Rajasthan, on governance vision for Rajasthan 2047.',
  'As part of RIC Foundation Day Celebrations, V. Srinivas speaks on governance transformation and the Rajasthan 2047 roadmap, including Q&A.',
  'Rajasthan International Centre Official Calendar',
  'https://ricjaipur.org/Uploads/Downloads/CalendarOfEvents.pdf',
  array['talk','governance','policy','seminar','jaipur']
),
(
  'qawwali-night-rehmat-e-nusrat-ric-jaipur-apr-2026',
  'Qawwali Night – by Rehmat-e-Nusrat',
  'Concert / Sufi Music',
  'music-events',
  'upcoming',
  '2026-04-22 18:30:00+05:30',
  '2026-04-22 20:15:00+05:30',
  'Rajasthan International Centre – Main Auditorium',
  'Sansthan Path, JLN Marg, Jaipur, Rajasthan 302017',
  'jhalana-doongri',
  null,
  false,
  'https://in.bookmyshow.com/plays/rajasthan-international-centre/ET00363555',
  'Rajasthan International Centre',
  null,
  'A soul-stirring Qawwali night by the acclaimed ensemble Rehmat-e-Nusrat at RIC''s Main Auditorium.',
  'Rajasthan International Centre presents Qawwali Night featuring Rehmat-e-Nusrat, bringing devotional Sufi music to Jaipur.',
  'Rajasthan International Centre Official Calendar',
  'https://ricjaipur.org/Uploads/Downloads/CalendarOfEvents.pdf',
  array['qawwali','sufi','music','concert','jaipur']
),
(
  'happy-huddle-gossip-girls-kids-popup-jaipur-apr-2026',
  'Happy Huddle X The Gossip Girls – Kids Pop-Up 2026',
  'Exhibition / Kids & Family',
  'kids-family',
  'upcoming',
  '2026-04-25 11:00:00+05:30',
  null,
  'Birla Auditorium',
  'BM Birla Auditorium, Statue Circle, C Scheme, Rambagh, Jaipur, Rajasthan 302015',
  'c-scheme',
  0,
  true,
  'https://ilovejaipur.city/events/happy-huddle-x-the-gossip-girls-kids-pop-up-2026/',
  'Happy Huddle',
  'https://ilovejaipur.city/media/events/2026/03/19_20260323_121738.jpg',
  'First-of-its-kind kids and family pop-up in Jaipur — kids fashion, toy brands, STEM, DIY, interactive learning and a Glow DJ Party.',
  'A vibrant world dedicated to kids and families with toy brands, fashion, STEM activities, DIY zones, interactive learning and a Glow DJ Party.',
  'ilovejaipur.city',
  'https://ilovejaipur.city/events/happy-huddle-x-the-gossip-girls-kids-pop-up-2026/',
  array['kids','family','pop-up','exhibition','STEM','jaipur']
),
(
  'art-vibes-mocktail-delights-jaipur-apr-2026',
  'Art, Vibes and Mocktail Delights',
  'Workshop / Art',
  'workshops',
  'upcoming',
  '2026-04-25 16:00:00+05:30',
  null,
  'Paro – Modern India Bar',
  'Panchbatti, C-Scheme, Ashok Nagar, Jaipur, Rajasthan',
  'c-scheme',
  1499,
  false,
  'https://ilovejaipur.city/events/art-vibes-and-mocktail-delights/',
  'Pretty Hairbrushes',
  'https://ilovejaipur.city/media/events/2026/04/127_20260411_093809.png',
  'Decorate your own hairbrush and jewellery box with gems and paint. All materials included plus a refreshing mocktail.',
  'An evening of creativity at Paro where participants decorate a hairbrush and jewellery box with all materials included plus a mocktail.',
  'ilovejaipur.city',
  'https://ilovejaipur.city/events/art-vibes-and-mocktail-delights/',
  array['workshop','art','DIY','jewellery','mocktail','jaipur']
),
(
  'pasandida-aurat-standup-comedy-jaipur-apr-2026',
  'Pasandida Aurat – A Standup Comedy Show',
  'Comedy',
  'comedy-shows',
  'upcoming',
  '2026-04-26 19:30:00+05:30',
  null,
  'Jaipur Comedy Club',
  'Jaipur Comedy Club, Jaipur, Rajasthan',
  'jaipur',
  300,
  false,
  'https://ilovejaipur.city/events/pasandida-aurat-a-standup-comedy-show/',
  'Jaipur Comedy Club',
  'https://ilovejaipur.city/media/events/2026/04/126_20260402_082311.png',
  'A hilarious standup comedy show. Come with your partner and experience a laughter night out.',
  'Pasandida Aurat is a Hindi standup comedy night at Jaipur Comedy Club, perfect for couples and comedy lovers.',
  'ilovejaipur.city',
  'https://ilovejaipur.city/events/pasandida-aurat-a-standup-comedy-show/',
  array['comedy','standup','jaipur comedy club','jaipur']
),
(
  'clay-modelling-with-puppies-cafesa-jaipur-apr-2026',
  'Clay Modelling With Puppies At Cafesa 2026',
  'Workshop / Activities',
  'workshops',
  'upcoming',
  '2026-04-26 11:00:00+05:30',
  '2026-04-26 12:00:00+05:30',
  'Cafesa Coffee House',
  'Cafesa Coffee House, Kirti Nagar, Shyam Nagar, Jaipur, Rajasthan',
  'shyam-nagar',
  679,
  false,
  'https://ilovejaipur.city/events/clay-modelling-with-puppies-at-cafesa-2026/',
  'Pawga',
  'https://ilovejaipur.city/media/events/2026/03/19_20260327_134554.jpg',
  '60-min clay modelling session with shelter puppies by Pawga. Therapeutic, creative and supports animal welfare.',
  'Pawga brings a creative clay modelling session with shelter puppies, combining art, therapy and animal welfare support.',
  'ilovejaipur.city',
  'https://ilovejaipur.city/events/clay-modelling-with-puppies-at-cafesa-2026/',
  array['workshop','clay','puppies','pets','animal welfare','jaipur']
),
(
  'gaurav-gupta-live-india-tour-jaipur-apr-2026',
  'Gaurav Gupta Live – India Tour (Jaipur)',
  'Comedy / Standup',
  'comedy-shows',
  'upcoming',
  '2026-04-26 19:30:00+05:30',
  '2026-04-26 20:45:00+05:30',
  'Maharana Pratap Auditorium',
  'Maharana Pratap Auditorium, Jaipur, Rajasthan',
  'jaipur',
  799,
  false,
  'https://allevents.in/jaipur/gaurav-gupta-live-india-tour/3900029619968431',
  null,
  'https://cdn-az.allevents.in/events5/banners/1753da20-2f4b-11f1-bec9-ad3f1e96ac99-rimg-w1200-h600-dc8dffe9-gmir.jpg?v=1775213498',
  'Gaurav Gupta (Being Baniya) brings his India Tour to Jaipur — 75 minutes of high-energy, relatable standup comedy in Hindi.',
  'Gaurav Gupta, known for Being Baniya and Market Down Hai, brings his India Tour to Jaipur for a 75-minute standup set.',
  'AllEvents.in',
  'https://allevents.in/jaipur/gaurav-gupta-live-india-tour/3900029619968431',
  array['comedy','standup','gaurav gupta','being baniya','jaipur']
),
(
  'truck-trailer-tyre-expo-jaipur-jun-2026',
  'Truck, Trailer & Tyre Expo 2026',
  'Trade Show / Automotive',
  'trade-shows',
  'upcoming',
  '2026-06-05 10:00:00+05:30',
  '2026-06-07 18:00:00+05:30',
  'Jaipur Exhibition & Convention Centre (JECC)',
  'Exhibition Ground, RIICO Industrial Area, Sitapura, Sanganer, Jaipur, Rajasthan 302022',
  'sitapura',
  0,
  true,
  'https://trucktrailerntyreexpo.com/',
  'Media Day Marketing',
  'https://cdn-az.allevents.in/events5/banners/28e6a217fbd675569cd569c490549abce6bdf14f763a2b9dc3e243d53c1405f0-rimg-w1200-h628-dc171515-gmir?v=1775563194',
  'Asia''s only expo dedicated to trucks, trailers and tyres — 3 days of product showcases, B2B networking and industry innovation at JECC Jaipur.',
  'Truck, Trailer & Tyre Expo 2026 is a major B2B trade show at JECC Jaipur for the commercial transport and tyre ecosystem.',
  'AllEvents.in / ShowsBee',
  'https://allevents.in/jaipur/truck-trailer-and-tyre-expo-2026/200029811548914',
  array['trade show','trucks','automotive','tyres','JECC','jaipur']
),
(
  'fashionista-fashion-lifestyle-exhibition-jaipur-nov-2026',
  'Fashionista Fashion & Lifestyle Exhibition Jaipur',
  'Exhibition / Fashion & Lifestyle',
  'exhibitions',
  'upcoming',
  '2026-11-16 11:00:00+05:30',
  '2026-11-17 21:00:00+05:30',
  'Birla Auditorium',
  'Birla Institute of Scientific Research, Central Park, Rambagh, Jaipur, Rajasthan 302005',
  'c-scheme',
  0,
  true,
  'https://allevents.in/jaipur/fashionista-fashion-and-lifestyle-exhibition-jaipur/200026281511008',
  'Fashionista Exhibition Private Limited',
  'https://cdn-az.allevents.in/events8/banners/f9e638ef9206c4808098290b60990cd2cc20b842408eccfbbe724a821ba6ca34-rimg-w960-h540-dcefdbed-gmir?v=1776041411',
  'Bespoke bridal couture, exclusive ensembles, breathtaking jewellery, footwear and accessories — Fashionista brings royal tradition back to life.',
  'Fashionista returns to Jaipur with a large fashion and lifestyle exhibition featuring bridal couture, jewellery, footwear and accessories.',
  'AllEvents.in',
  'https://allevents.in/jaipur/fashionista-fashion-and-lifestyle-exhibition-jaipur/200026281511008',
  array['exhibition','fashion','bridal','lifestyle','jewellery','jaipur']
);

insert into public.categories (name, slug, is_indexable)
values
  ('Art & Culture', 'art-culture', true),
  ('Music Events', 'music-events', true),
  ('Exhibitions', 'exhibitions', true),
  ('Business & Education', 'business-education', true),
  ('Kids & Family', 'kids-family', true),
  ('Workshops', 'workshops', true),
  ('Comedy Shows', 'comedy-shows', true),
  ('Trade Shows', 'trade-shows', true)
on conflict (slug) do update
set
  name = excluded.name,
  is_indexable = true;

insert into public.events (
  title,
  slug,
  category,
  tags,
  status,
  editorial_status,
  is_indexable,
  published_at,
  updated_at,
  start_time,
  end_time,
  venue_name,
  venue_address,
  locality,
  ticket_price,
  is_free,
  registration_url,
  organizer_name,
  image_url,
  cover_image_url,
  cover_image,
  short_description,
  description,
  meta_title,
  meta_description,
  source_label,
  source_url
)
select
  se.title,
  se.slug,
  se.category_label,
  se.tags,
  lower(se.status),
  'published',
  true,
  now(),
  now(),
  se.start_time,
  se.end_time,
  se.venue_name,
  se.venue_address,
  se.locality,
  se.ticket_price,
  coalesce(se.is_free, false),
  se.registration_url,
  se.organizer_name,
  se.image_url,
  se.image_url,
  se.image_url,
  se.short_description,
  se.description,
  se.title,
  se.short_description,
  se.source_label,
  se.source_url
from seed_events se
on conflict (slug) do update
set
  title = excluded.title,
  category = excluded.category,
  tags = excluded.tags,
  status = excluded.status,
  editorial_status = excluded.editorial_status,
  is_indexable = excluded.is_indexable,
  updated_at = now(),
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  venue_name = excluded.venue_name,
  venue_address = excluded.venue_address,
  locality = excluded.locality,
  ticket_price = excluded.ticket_price,
  is_free = excluded.is_free,
  registration_url = excluded.registration_url,
  organizer_name = excluded.organizer_name,
  image_url = excluded.image_url,
  cover_image_url = excluded.cover_image_url,
  cover_image = excluded.cover_image,
  short_description = excluded.short_description,
  description = excluded.description,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  source_label = excluded.source_label,
  source_url = excluded.source_url;

insert into public.event_categories (event_id, category_id)
select
  e.id,
  c.id
from seed_events se
join public.events e
  on e.slug = se.slug
join public.categories c
  on c.slug = se.category_slug
on conflict do nothing;

commit;
